CREATE DATABASE IF NOT EXISTS Charter;
USE Charter;

CREATE TABLE IF NOT EXISTS Crew (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    Name VARCHAR(20) NOT NULL,
    Surname VARCHAR(20) NOT NULL,
    Position VARCHAR(20) NOT NULL,
    Price VARCHAR(20) NOT NULL,
    Review VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS Company (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    Name VARCHAR(20) NOT NULL,
    Location VARCHAR(20) NOT NULL,
    Email VARCHAR(40) NOT NULL,
    Password VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    Name VARCHAR(20) NOT NULL,
    Surname VARCHAR(20) NOT NULL,
    License VARCHAR(20) NOT NULL,
    Email VARCHAR(40) NOT NULL,
    Password VARCHAR(40) NOT NULL,
    Date_Of_Birth DATE,
    Gender VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Payment (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    OIB VARCHAR(40) NOT NULL,
    IBAN VARCHAR(40) NOT NULL,
    User_ID CHAR(36) NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Boats (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    Company_ID CHAR(36) NOT NULL,
    Img VARCHAR(100),
    Price VARCHAR(20) NOT NULL,
    Availability VARCHAR(20) NOT NULL,
    Review VARCHAR(20),
    FOREIGN KEY (Company_ID) REFERENCES Company(ID)
);

CREATE TABLE IF NOT EXISTS Reservation (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    User_ID CHAR(36) NOT NULL,
    Boat_ID CHAR(36) NOT NULL,
    Start_Date DATETIME,
    End_Date DATETIME,
    Down_Payment VARCHAR(20) NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(ID),
    FOREIGN KEY (Boat_ID) REFERENCES Boats(ID)
);

CREATE TABLE IF NOT EXISTS BoatType (
    ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    Name VARCHAR(20) NOT NULL,
    Type VARCHAR(20) NOT NULL,
    Passenger_Capacity INT,
    Length VARCHAR(20) NOT NULL,
    Width VARCHAR(20) NOT NULL,
    Height VARCHAR(20) NOT NULL,
    Crew_Capacity INT
);

CREATE TABLE IF NOT EXISTS CrewCompany (
    Crew_ID CHAR(36) NOT NULL,
    Company_ID CHAR(36) NOT NULL,
    PRIMARY KEY (Crew_ID, Company_ID),
    FOREIGN KEY (Crew_ID) REFERENCES Crew(ID),
    FOREIGN KEY (Company_ID) REFERENCES Company(ID)
);

CREATE TABLE IF NOT EXISTS CrewReservation (
    Crew_ID CHAR(36) NOT NULL,
    Reservation_ID CHAR(36) NOT NULL,
    PRIMARY KEY (Crew_ID, Reservation_ID),
    FOREIGN KEY (Crew_ID) REFERENCES Crew(ID),
    FOREIGN KEY (Reservation_ID) REFERENCES Reservation(ID)
);