ALTER TABLE Crew
ADD COLUMN company_id CHAR(36) NOT NULL,
ADD FOREIGN KEY (company_id) REFERENCES Company(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Payment
DROP COLUMN user_id,
ADD COLUMN user_id CHAR(36) NOT NULL,
ADD FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Boats
DROP COLUMN company_id,
ADD COLUMN company_id CHAR(36) NOT NULL,
ADD FOREIGN KEY (company_id) REFERENCES Company(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Reservation
DROP COLUMN user_id,
DROP COLUMN boat_id,
ADD COLUMN user_id CHAR(36) NOT NULL,
ADD COLUMN boat_id CHAR(36) NOT NULL,
ADD FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (boat_id) REFERENCES Boats(id) ON DELETE CASCADE ON UPDATE CASCADE;

DROP TABLE CrewCompany;

ALTER TABLE CrewReservation
DROP COLUMN crew_id,
DROP COLUMN reservation_id,
ADD COLUMN crew_id CHAR(36) NOT NULL,
ADD COLUMN reservation_id CHAR(36) NOT NULL,
ADD FOREIGN KEY (crew_id) REFERENCES Crew(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (reservation_id) REFERENCES Reservation(id) ON DELETE CASCADE ON UPDATE CASCADE;